# MCTS
C_PUCT = 2**0.5
EPSILON = 0.25  # P = (1 - EPSILON) * P + EPSILON * noise
ALPHA = 0.03  # Dirichlect noise
VIRTUAL_DISCOUNT = 0.9
DEFAULT_PARALLEL_NUM = 8
NUM_DEFAULT_SEARCH_STEPS = 512

# Game
BOARD_SHAPE = (9, 9)
NUM_CONNECTED_TO_WIN = 5
GUIDED_BOARD = False

# Network
L2_PENALTY = 1e-3
NUM_RESIDUAL_BLOCKS = 2
NUM_NETWORK_UNITS = 64

# Misc
DEFAULT_MODEL_PATH = '../model/model.nn'
DEFAULT_DATA_PATH = '../data/data.np'
